apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-agent-ci
  namespace: tekton-pipelines
  labels:
    app: github-agent
    pipeline-type: ci
spec:
  description: Basic CI pipeline for testing and validation on feature branches
  params:
    - name: git-url
      type: string
      description: Git repository URL
      default: https://github.com/your-org/github-issue-agent.git
    - name: git-revision
      type: string
      description: Git revision (branch/tag/commit)
      default: main
    - name: image-registry
      type: string
      description: Container registry URL
      default: gcr.io/your-project-id
    - name: image-name
      type: string
      description: Image name
      default: github-agent
    - name: image-tag
      type: string
      description: Image tag
      default: ci-latest
  
  workspaces:
    - name: shared-workspace
      description: Shared workspace for pipeline tasks
    - name: dockerconfig
      description: Docker config for registry authentication
  
  tasks:
    # 1. Clone source code
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
    
    # 2. Run unit and integration tests
    - name: run-tests
      taskRef:
        name: run-tests
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
    
    # 3. Build Docker image with Kaniko
    - name: build-image
      taskRef:
        name: kaniko-build
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: image
          value: "$(params.image-registry)/$(params.image-name):$(params.image-tag)"
        - name: dockerfile
          value: ./docker/prod-optimized.Dockerfile
        - name: extra-args
          value:
            - --build-arg=ENVIRONMENT=ci
            - --cache=true
    
    # 4. Security scan with Trivy
    - name: security-scan
      taskRef:
        name: trivy-scan
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image
          value: "$(params.image-registry)/$(params.image-name):$(params.image-tag)"
        - name: severity
          value: "HIGH,CRITICAL"
