apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: staging-pipeline
  namespace: tekton-pipelines
  labels:
    environment: staging
spec:
  description: Staging pipeline - triggered on merge to main branch
  params:
    - name: git-url
      type: string
      description: Git repository URL
      default: https://github.com/your-org/github-issue-agent.git
    - name: git-revision
      type: string
      description: Git revision to build
      default: main
    - name: image-registry
      type: string
      description: Harbor registry URL
      default: harbor.example.com
    - name: image-name
      type: string
      description: Image name
      default: github-agent
    - name: image-tag
      type: string
      description: Image tag
    - name: sonar-host-url
      type: string
      description: SonarQube server URL
      default: http://sonarqube:9000
  
  workspaces:
    - name: shared-workspace
    - name: docker-credentials
    - name: git-credentials
      optional: true
  
  tasks:
    # 1. Clone source code
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    
    # 2. Run unit tests
    - name: run-tests
      taskRef:
        name: run-tests
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: python-version
          value: "3.11"
    
    # 3. Run SonarQube scan with quality gate
    - name: code-quality-scan
      taskRef:
        name: sonar-scanner
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: sonar-host-url
          value: $(params.sonar-host-url)
        - name: sonar-project-key
          value: github-issue-agent-staging
    
    # 4. Build Docker image
    - name: build-image
      taskRef:
        name: kaniko-build
      runAfter:
        - code-quality-scan
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: image
          value: $(params.image-registry)/agent-staging/$(params.image-name):$(params.image-tag)
        - name: dockerfile
          value: ./docker/prod-optimized.Dockerfile
        - name: extra-args
          value:
            - --build-arg=ENVIRONMENT=staging
            - --label=git-commit=$(tasks.fetch-repository.results.commit)
            - --label=build-date=$(tasks.fetch-repository.results.committer-date)
    
    # 5. Security scan with strict policy
    - name: security-scan
      taskRef:
        name: trivy-scan
      runAfter:
        - build-image
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
      params:
        - name: image
          value: $(params.image-registry)/agent-staging/$(params.image-name):$(params.image-tag)
        - name: severity
          value: "CRITICAL,HIGH"
        - name: exit-code
          value: "1"  # Fail on critical/high vulnerabilities
    
    # 6. Update staging manifest
    - name: update-manifest
      taskRef:
        name: update-manifest
      runAfter:
        - security-scan
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: git-credentials
          workspace: git-credentials
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: main
        - name: manifest-dir
          value: k8s/overlays/staging
        - name: image-name
          value: $(params.image-registry)/agent-staging/$(params.image-name)
        - name: image-tag
          value: $(params.image-tag)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: staging-pipeline-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push-main
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secret
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/main'"
      bindings:
        - ref: staging-pipeline-binding
      template:
        ref: staging-pipeline-template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: staging-pipeline-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
      value: $(body.ref)
    - name: git-commit-id
      value: $(body.head_commit.id)
    - name: git-repo-url
      value: $(body.repository.clone_url)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: staging-pipeline-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-revision
    - name: git-commit-id
    - name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: staging-pipeline-run-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: staging-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: main
          - name: image-tag
            value: staging-$(tt.params.git-commit-id)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: docker-credentials
            secret:
              secretName: harbor-credentials
          - name: git-credentials
            secret:
              secretName: git-credentials
